import { request } from 'http';
import type { NextPage, GetServerSideProps, NextPageContext } from 'next';
import Head from 'next/head';
import Image from 'next/image';

import Header from '../components/Header';
import Navbar from '../components/Navbar';
import Results from '../components/Results';
import requests from '../utils/requests';

interface HomeProps {
  results: any;
}

const Home: NextPage<HomeProps> = ({ results }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* Nav */}
      <Navbar />

      {/* Results */}
      <Results requests={results} />
    </div>
  );
};

export async function getServerSideProps(context: any) {
  const genre: any = context.query.genre as string;

  let request: any;
  if (typeof genre === 'string') {
    request = await fetch(
      `https://api.themoviedb.org/3${
        requests[genre]?.url || requests.fetchTrending.url
      }`
    )
      .then((res: any) => res.json())
      .catch((err) => console.log('err : ', err));
  }

  return {
    props: {
      results: request.results,
    },
  };
}

export default Home;
